version: "3.8"

services:
#  web:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    depends_on:
#      - mongodb
#    environment:
#      - MONGODB_URL=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
